# FILENAME: configs/mujoco_humanoid.yaml
# Humanoid-v4 with PPO - Most complex locomotion task

experiment:
  name: "humanoid_ppo_experiment"
  save_dir: "./experiments"
  seed: 42

environment:
  name: "Humanoid-v4"
  type: "gym"
  max_episode_steps: 1000
  normalize_observations: true
  normalize_rewards: true
  frame_skip: 1

algorithm:
  name: "PPO"
  learning_rate: 2e-4  # Slightly lower for stability
  gamma: 0.99
  lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.0
  critic_coef: 1.0
  max_grad_norm: 0.5
  num_epochs: 15  # More epochs for complex task
  batch_size: 512  # Larger batches
  num_cells: 1024  # Large network for complex morphology
  activation: "tanh"

training:
  total_frames: 5000000  # Very long training
  frames_per_batch: 8192  # Large batches
  eval_frequency: 200
  eval_episodes: 5  # Fewer eval episodes due to length
  save_frequency: 500
  log_frequency: 50

hyperparameter_optimization:
  enabled: false  # Start without hyperopt for such complex tasks
  method: "GP-UCB"
  t_ready: 500000
  bounds:
    learning_rate: [1e-5, 5e-4]
    clip_epsilon: [0.1, 0.3]
    lambda: [0.9, 1.0]

logging:
  tensorboard: true
  wandb: false
  save_models: true
  save_videos: true
  log_activations: false
  log_level: "INFO"