# FILENAME: configs/mujoco_walker2d.yaml
# Walker2d-v4 with PPO - Bipedal walking

experiment:
  name: "walker2d_ppo_experiment"
  save_dir: "./experiments"
  seed: 42

environment:
  name: "Walker2d-v4"
  type: "gym"
  max_episode_steps: 1000
  normalize_observations: true
  normalize_rewards: true
  frame_skip: 1

algorithm:
  name: "PPO"
  learning_rate: 3e-4
  gamma: 0.99
  lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.0
  critic_coef: 1.0
  max_grad_norm: 0.5
  num_epochs: 10
  batch_size: 256
  num_cells: 256
  activation: "tanh"

training:
  total_frames: 1500000
  frames_per_batch: 2048
  eval_frequency: 75
  eval_episodes: 10
  save_frequency: 150
  log_frequency: 15

hyperparameter_optimization:
  enabled: false
  method: "GP-UCB"
  t_ready: 150000
  bounds:
    learning_rate: [1e-5, 1e-3]
    clip_epsilon: [0.1, 0.3]
    lambda: [0.9, 1.0]

logging:
  tensorboard: true
  wandb: false
  save_models: true
  save_videos: true
  log_activations: false
  log_level: "INFO"
