# FILENAME: configs/mujoco_ant.yaml
# Ant-v4 with PPO - More complex quadruped locomotion

experiment:
  name: "ant_ppo_experiment"
  save_dir: "./experiments"
  seed: 42

environment:
  name: "Ant-v4"
  type: "gym"
  max_episode_steps: 1000
  normalize_observations: true
  normalize_rewards: true
  frame_skip: 1

algorithm:
  name: "PPO"
  learning_rate: 3e-4
  gamma: 0.99
  lambda: 0.95
  clip_epsilon: 0.2
  entropy_coef: 0.0
  critic_coef: 1.0
  max_grad_norm: 0.5
  num_epochs: 10
  batch_size: 256
  num_cells: 512  # Larger network for more complex task
  activation: "tanh"

training:
  total_frames: 2000000  # Longer training for complex morphology
  frames_per_batch: 4096
  eval_frequency: 100
  eval_episodes: 10
  save_frequency: 200
  log_frequency: 20

hyperparameter_optimization:
  enabled: false
  method: "GP-UCB"
  t_ready: 200000
  bounds:
    learning_rate: [1e-5, 1e-3]
    clip_epsilon: [0.1, 0.3]
    lambda: [0.9, 1.0]
    num_cells: [256, 1024]

logging:
  tensorboard: true
  wandb: false
  save_models: true
  save_videos: true
  log_activations: false
  log_level: "INFO"

